"""add created_at to clinical_encounters

Revision ID: 17f5b9704313
Revises: 8045226c5429
Create Date: 2026-02-12 22:45:10.480316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f5b9704313'
down_revision: Union[str, Sequence[str], None] = '8045226c5429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_encounters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_encounters', 'created_at')
    # ### end Alembic commands ###
