"""make fields nullable

Revision ID: aa0454f42e77
Revises: 65e12de54a95
Create Date: 2026-02-12 22:23:05.337503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0454f42e77'
down_revision: Union[str, Sequence[str], None] = '65e12de54a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_encounters', sa.Column('patient_age', sa.Integer(), nullable=True))
    op.alter_column('clinical_encounters', 'patient_gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinical_encounters', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinical_encounters', 'ai_response',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('clinical_encounters', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('clinical_encounters', 'pattient_age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_encounters', sa.Column('pattient_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('clinical_encounters', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('clinical_encounters', 'ai_response',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('clinical_encounters', 'audio_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clinical_encounters', 'patient_gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clinical_encounters', 'patient_age')
    # ### end Alembic commands ###
