"""add updated_at to clinical_encounters

Revision ID: cdcd0f093a2f
Revises: 17f5b9704313
Create Date: 2026-02-12 22:50:29.239470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdcd0f093a2f'
down_revision: Union[str, Sequence[str], None] = '17f5b9704313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_encounters', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_encounters', 'updated_at')
    # ### end Alembic commands ###
