"""fix nullable fields and types

Revision ID: e3c94610f93e
Revises: aa0454f42e77
Create Date: 2026-02-12 22:30:40.257115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3c94610f93e'
down_revision: Union[str, Sequence[str], None] = 'aa0454f42e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_encounters', sa.Column('retrieved_chunks', sa.JSON(), nullable=True))
    op.alter_column('clinical_encounters', 'transcript',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('clinical_encounters', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clinical_encounters', 'model_used',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinical_encounters', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('clinical_encounters', 'retrived_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_encounters', sa.Column('retrived_chunks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('clinical_encounters', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clinical_encounters', 'model_used',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clinical_encounters', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clinical_encounters', 'transcript',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('clinical_encounters', 'retrieved_chunks')
    # ### end Alembic commands ###
